name = input("Enter your dad's name| ")
print("...")
print(name) 
print("------")
phone = input("Enter your dad's phone number| ")
print("...")
print(phone)
print("------")
address = input("Enter your dad's address| ")
print("...")
print(address)
print("------")
print("Now lets do math")
print("...")
number1 = float(input("Enter number1|"))
print("...")
number2 = float(input("Enter number2|"))
print("...")
operator = input("Enter an operator(+,-,*,/):")
print("My cousin just finished it")
print("^^^")
if operator == "+":
	print(number1+number2)
elif operator == "-":
	print(number1-number2)
elif operator == "*":
	print(number1*number2)
elif operator == "/":
	print(number1/number2)
